SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)

SET(CMAKE_C_COMPILER x86_64-w64-mingw32-clang)
SET(CMAKE_CXX_COMPILER x86_64-w64-mingw32-clang++)
SET(CMAKE_RC_COMPILER_INIT x86_64-w64-mingw32-windres)
SET(CMAKE_ASM_COMPILER x86_64-w64-mingw32-as)

LIST(APPEND CMAKE_PROGRAM_PATH /mingw64/bin ...)
SET(CMAKE_FIND_ROOT_PATH /mingw64/mingw)
SET(CMAKE_INSTALL_PREFIX /mingw64/mingw)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
